### ISSUE TITLE
ROS1 message built-in field type: time

### ISSUE THREAD

**Issue by fkromer** [ros-testing/hypothesis-ros#13]
[wiki.ros.org - 2.1.1 Field Types](http://wiki.ros.org/msg#Fields)

**Comment by fkromer** [comment]
@Minipada Sorry for hijacking your PR. I need it soon and I didn't want to wait for it :wink:.

https://github.com/ros-testing/hypothesis-ros/commit/4bc60c655db84b98f79343f024870f7ee49724b5

**Comment by Minipada** [comment]
@fkromer No problem, I got extremely busy in the last week. Thanks.
