### ISSUE TITLE
General review and suggestions

### ISSUE THREAD

**Issue by Zac-HD** [ros-testing/hypothesis-ros#48]
I'm so excited to see this that I've been skimming through the code, and thought it might be helpful to share my notes on anything we'd do differently upstream.

- For the various field type strategies, you rely on users passing `min_value` and `max_value` arguments that are representable for that type.  But if e.g. a user calls `uint8(-100, 999)`, they'll get ROS errors that are really from bad input!  Suggestion: put the following code in each, possibly in a helper function: `if not (MIN_XXX_VALUE <= min_value <= max_value <= MAX_XXX_VALUE): raise InvalidArgument`

- I do like the approach of passing strategies for `secs` and `nsecs` to `durations`, but I'd also check that the values you draw are within the int32 range (not just of python type int).

- The `arrays` message has an error in the docstring; while `unique_by` must be a callable, `unique` is simply a boolean.

- In `parameters.py`, you could avoid redefining int32/string/bool by simply using `from message_fields import int32, string, bool, array as list` and adding them to an `__all__` variable to signal that they are public API.

- You often define names that overwrite builtins (e.g. bool, list) or standard library modules (e.g. string).  This does *work* at runtime, but I'd try to avoid it for the sake of clarity for users.

- Not saying you shouldn't, but what's the advantage of redefining strategies built into Hypothesis?  Specifically thinking of bools, lists/arrays, and float64 here.  Would documentation of the upstream option work, or is providing everything a better user experience for ROS?  (if so, consider the import trick above)

- The geometry, sensor, and std messages all look great :heart_eyes: 

And finally, congratulations on building an awesome package!

**Comment by fkromer** [comment]
> I'm so excited to see this that I've been skimming through the code, and thought it might be helpful to share my notes on anything we'd do differently upstream.

Thx for the notes. I will go through it and comment/fix it asap (will take some time :slightly_smiling_face:  ).

> And finally, congratulations on building an awesome package!

You played a significant role (hints, reviews, etc.) in making this package happen. Thx a lot again! [hypothesis](https://github.com/HypothesisWorks/hypothesis) is great!

**Comment by fkromer** [comment]
> - For the various field type strategies, you rely on users passing min_value and max_value arguments that are representable for that type. But if e.g. a user calls uint8(-100, 999), they'll get ROS errors that are really from bad input! Suggestion: put the following code in each, possibly in a helper function: if not (MIN_XXX_VALUE <= min_value <= max_value <= MAX_XXX_VALUE): raise InvalidArgument

Right. As default values lower and upper bound values are preconfigured. If one does not know how to use the helper functions one can totally mess up things. So far validation is hardly existing. That's on my todo list.

> - I do like the approach of passing strategies for secs and nsecs to durations, but I'd also check that the values you draw are within the int32 range (not just of python type int).

As far as I know the ROS framework does not allow to publish "communication context" out-of-bound values. From a data type point of view one could generate the full range of values. But this would lead to false positives. (It would be possible to throw "full data type range" values at nodes. But the scenario where this would be reasonable is rare: ROS1 nodes are not suitable for cloud robotics and the like where they could be exposed to a bigger scope than an application specific set of collaborating nodes in a "closed" network.)

> - The arrays message has an error in the docstring; while unique_by must be a callable, unique is simply a boolean.

Thx. To be fixed.

> - In parameters.py, you could avoid redefining int32/string/bool by simply using from message_fields import int32, string, bool, array as list and adding them to an __all__ variable to signal that they are public API.

Thx. Do you have some example source code?

> You often define names that overwrite builtins (e.g. bool, list) or standard library modules (e.g. string). This does work at runtime, but I'd try to avoid it for the sake of clarity for users.

I know. That's ugly. So far I sticked to this "official" ROS notations to make it easier to map `hypothesis-ros` helpers to ROS data type notation.

> Not saying you shouldn't, but what's the advantage of redefining strategies built into Hypothesis? Specifically thinking of bools, lists/arrays, and float64 here. Would documentation of the upstream option work, or is providing everything a better user experience for ROS? (if so, consider the import trick above)

The reason is the same as mentioned for "I do like the approach of passing strategies for secs and nsecs to durations, but I'd also check that the values you draw are within the int32 range (not just of python type int)." 

> The geometry, sensor, and std messages all look great heart_eyes

Thx.

**Comment by Zac-HD** [comment]
> I am not quite sure if I shall add validation or not because [ROS won't publish bad messages]

That's actually a reason *to* validate up front - it means you get exceptions as close to the actual error as possible!  It's also the Hypothesis idiom :smile: 

> Do you have some example source code?

```python
__all__ = ['a', 'c', 'd']
from x import a, b as c
def d(): ...
```

[More here](https://github.com/HypothesisWorks/hypothesis/blob/master/hypothesis-python/src/hypothesis/__init__.py), though we don't have any reason to use the `as` trick.

> So far I sticked to this "official" ROS notations to make it easier to map `hypothesis-ros` helpers to ROS data type notation.

This is a good design principle, and worth continuing!  I'd make sure to point this out in the docs though, and explain why you're using the names (just a sentence or two would be enough) so that pythonistas understand.

**Comment by fkromer** [comment]
> I am not quite sure if I shall add validation or not because [ROS won't publish bad messages]

I know :smile: . ROS dos not publish bad messages ("ROS application" publisher scenario) but you or me could ("blackhat" publisher scenario). One should never ever allow "blackhat" messages reach a ROS node graph (ROS notation for "network of nodes") with higher level measures. But it would be possible. I thought about some configuration option to enable/disable validation but this would make things more complex than required. As there is practically (hopefully) no ROS node usage scenario which would make a "blackhat" usage of `hypothesis-ros` reasonable I will add the validation. In case one could add a configuration option later.

> `__all__ = ['a', 'c', 'd']
from x import a, b as c
def d(): ...`
> More here, though we don't have any reason to use the as trick.

Thx. Would help to implement the validation for supported strategies in [array() elements](https://github.com/ros-testing/hypothesis-ros/blob/8e369bae7202a437dd3d1216b87855126f09c02e/hypothesis_ros/message_fields.py#L393) as well. Right, no `as` needed here.

> I'd make sure to point this out in the docs though, and explain why you're using the names (just a sentence or two would be enough) so that pythonistas understand.

Good point.

Thx for the review. Feel free to point out whatever else comes to your mind which improves the package :wink:

**Comment by fkromer** [comment]
https://github.com/ros-testing/hypothesis-ros/commit/5d9df608fec9f80730392e51ffe90af2692599e9

**Comment by fkromer** [comment]
https://github.com/ros-testing/hypothesis-ros/commit/a20aa3986e10fade712af23622dd60103f0b72e0

**Comment by fkromer** [comment]
https://github.com/ros-testing/hypothesis-ros/commit/3e06a50dbf5d5562258058883c6b897cba5dcb49
